version: "2"
run:
  go: 1.25.8
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
#    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - '**/*.go'
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    dupl:
      threshold: 250
    funlen:
      lines: 120
      statements: 50
      ignore-comments: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 16
    gosec:
      excludes:
        - G101
        - G115
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    revive:
      confidence: 0.1
      rules:
        - name: var-naming
          arguments:
            - - SLA
    staticcheck:
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
        - SIP
        - RTP
        - AMQP
        - DB
        - TS
      checks:
        - all
        - '-QF1008' # знак '-' отключает проверку

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
      - linters:
          - govet
        text: declaration of "err" shadows declaration at .+
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
      - linters:
          - nolintlint
        text: //nolint:gosec
    paths:
      - \.pb\.go$
      - \.pb\.validate\.go$
      - \.pb\.gw\.go$
      - vendor
      - mock
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/razielsd/mcp-go-exports)
        - blank
        - dot
      custom-order: true
    gofumpt:
      extra-rules: false
  exclusions:
    generated: lax
    paths:
      - \.pb\.go$
      - \.pb\.validate\.go$
      - \.pb\.gw\.go$
      - vendor
      - mock
      - third_party$
      - builtin$
      - examples$
